#!/bin/bash
date "+Starting time: %c"
# Here is to define the job array
[setting]

# how many CPU for each job element
#BSUB -n 1
#BSUB -N

#BSUB -R "swp > 1000 && mem > 2000"
##BSUB -x
##BSUB -w done(panalyze_"$balp"_$cname)

# getting to the working dir
cd autism_precision_medicine


R -q -e "source('pCor.R'); pCor(\"$fnin\", $s1, $e1, $s2, $e2, \"$fnout\")"

date "+End time: %c"
# end of job script
